### PR TITLE
Feature/migration generator

### PR DESCRIPTION
**Pull request by rshiva**
Rather than adding migration manually, instead added the migration to rails generator.

### CODE REVIEW

**Comment by iyuuya** [comment]
I think this feature is very nice.
But coding style is not good :(

first, I want you to fix indent and EoF.
I do not use TAB character, please use 2 space.
Please insert a newline at end of file.

image

Use single quotes as much as possible.
`"` → `'`

**Comment by rshiva** [comment]
@iyuuya Sure I will fix the indentation and use 2 space instead of tab :)

**Comment by rshiva** [comment]
@iyuuya fixed the coding style as per you need :)

**Comment by iyuuya** [comment]
@rshiva please rebase master!
thx

**Comment by rshiva** [comment]
Done! Please check :)

**Pull request merged**
